name: Angle Bot

on:
  workflow_dispatch:

  schedule:
    # 14:00 Iran time
    # 10:30 UTC
    # Every day except Friday
    - cron: "30 10 * * 0-3,5-6"

jobs:
  angle:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Pillow
        run: |
          python -c "from PIL import Image, ImageDraw, ImageFont; print('Pillow OK')"

      - name: Run Angle Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: |
          echo "======================================"
          echo "Starting Angle Bot"
          echo "UTC time:"
          date -u
          echo "Iran time:"
          TZ=Asia/Tehran date
          echo "======================================"

          python angle.py

          echo "======================================"
          echo "Angle Bot finished"
          echo "======================================"
