name: Daily Calendar

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Send today's date
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python bot.py