name: Daily Market

on:
  schedule:
    - cron: '31 4 * * *'
  workflow_dispatch:

jobs:
  market:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: pip install requests beautifulsoup4

      - name: Run market bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python market.py