name: Price Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  price-test:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Run price test
        run: python price.py