name: Steel Market

on:
  workflow_dispatch:

  schedule:
    - cron: "35 4 * * *"

jobs:
  steel:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install lxml

      - name: Run Steel Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: |
          echo "======================================"
          echo "Starting Steel Market"
          echo "UTC time:"
          date -u
          echo "Iran time:"
          TZ=Asia/Tehran date
          echo "======================================"

          python steel.py

          echo "======================================"
          echo "Steel bot finished"
          echo "======================================"